server:
  # 端口
  port: 8089
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///jdd_college_club_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:///jdd_college_club_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
  redis:
    expire: 60000
    database: 0 # Redis使用的库
    host: 192.168.243.128
    port: 6379 #端口号
    password: jwj422123  #redis密码
    #    lettuce:
    #      pool:
    #        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
    #        max-wait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-idle: 8       # 连接池中的最大空闲连接
    #        min-idle: 1       # 连接池中的最小空闲连接
    timeout: 10000        #  连接超时时间（毫秒）
    cache:
      type: redis

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略实体表中的@TableLogic)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 使用默认的控制台输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/xml/*.xml
#jwt配置
jwt:
  secret: com.jdd.jxx
  #30分钟过期
  expiration: 1800000
# 放行的Url
permitUrl:
  loginUrl: /api/sys_user/login
  registerUrl: /api/sys_user/register
  imageCodeUrl: /api/sys_user/image

#logging:
#  pattern:
#    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'