server:
  # 端口
  port: 8089
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql:///jdd_college_club_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:///jdd_college_club_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略实体表中的@TableLogic)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 使用默认的控制台输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/xml/*.xml
#jwt配置
jwt:
  secret: com.jdd.jxx
  #30分钟过期
  expiration: 1800000
#登录请求配置
#itmk:
#  loginUrl: /api/user/login
#  imageCodeUrl: /api/sysUser/image
#logging:
#  pattern:
#    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'